### ISSUE TITLE
Chapter12 Websocket in pending 101 switching protocols status

### ISSUE THREAD

**Issue by johnnyquestep** [normanmaurer/netty-in-action#29]
I was able to build the jar and deploy to a linux server.
when i hit the ip:port it shows me the index.html file
Now i hit connect and i can see the status change to 101 switching protocol
i tried to send a message. it says message not sent in the log section then i see a response with the message i sent.
i also see it in the frames.
is that expected ? 

---
## below is related to websocket sample in netty.io site.

so i decided to run the examples in the netty.io site which is just supposed to return uppercase of the message.
this one worked on a linux machine, but kept getting error 400 on a solaris machine with chrome only saying that (opcode 1) in the frames. Then i tried wireshark, there i was able to see error message saying "upgrade" is missing. 
so i inspected the headers and matched up against the rfc and all the header were there.
Any ideas ? 

that sample i had 2 different experiences, i export the jar and ran it as a independent jar on a windows and linux pc no issues.
when i run it directly from eclipse it got suck unable to send any message when i debugged it said it failed at the point where it was trying get the web socket version from header. At this point i saw hat the constant defined or header value was all lowercase but the hearder had uppercase in it. 

Not sure how that worked when when i ran it outside of eclipse.

**Comment by johnnyquestep** [comment]
This is what i see in wireshark for the 400 bad request scenario.

GET /websocket HTTP/1.1
Host: x.x.x.x:8080
Connection: Upgrade
Pragma: no-cache
Cache-Control: no-cache
Upgrade: websocket
Origin: http://x.x.x.x:8080
Sec-WebSocket-Version: 13
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8
Sec-WebSocket-Key: uT0Y/9AfO+fwqw8BnaYiTg==
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits

HTTP/1.1 400 Bad Request

not a WebSocket handshake request: missing upgrade

**Comment by johnnyquestep** [comment]
netty version 4.1.5

**Comment by johnnyquestep** [comment]
this is an issue only on Solaris due to a platform dependent case insensitive hash comparison failure. fix will be in 4.1.7 #

**Comment by qwtsc** [comment]
FYI, "Message not sent" shown in the log section can be attributed to that the websocket.send can only return void no matter whether it suceeds or not according to the signature of send(data: string | ArrayBufferLike | Blob | ArrayBufferView): void; in the lib.dom.d.ts.
